### ISSUE TITLE
Fix `merge_lines` 

### ISSUE THREAD

**Issue by fnattino** [CityRiverSpaces/rcoins#6]
As pointed out by the linter, the cyclomatic complexity of this function is too high. Fix repeated content and integrate the auxiliary function with the other [very similar function](https://github.com/CityRiverSpaces/rcoins/blob/ff7b6cf88a957d5068f3d452f86eb5594a240772/R/stroke.R#L119): 

https://github.com/CityRiverSpaces/rcoins/blob/ff7b6cf88a957d5068f3d452f86eb5594a240772/R/stroke.R#L215-L223

**Comment by SarahAlidoost** [comment]
I suggest putting all the `while` loop in a separate function and calling it later in `merge_lines` function.

**Comment by fnattino** [comment]
Done!
